"""simplify_recipe_permissions_remove_granted_by

Revision ID: 510ad8dc9af4
Revises: 63f38b4e7979
Create Date: 2025-10-31 03:09:47.215405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '510ad8dc9af4'
down_revision = '63f38b4e7979'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_permission_recipe_role', table_name='recipe_permissions')
    op.drop_constraint('recipe_permissions_granted_by_fkey', 'recipe_permissions', type_='foreignkey')
    op.drop_column('recipe_permissions', 'granted_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_permissions', sa.Column('granted_by', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
    op.create_foreign_key('recipe_permissions_granted_by_fkey', 'recipe_permissions', 'users', ['granted_by'], ['id'])
    op.create_index('idx_permission_recipe_role', 'recipe_permissions', ['recipe_id', 'role'], unique=False)
    # ### end Alembic commands ###