"""Update recipe ingredient instruction models with tags subtext ordering

Revision ID: 63f38b4e7979
Revises: 0c9039fa718a
Create Date: 2025-10-29 17:09:39.818643

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "63f38b4e7979"
down_revision = "0c9039fa718a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ingredients", sa.Column("subtext", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "ingredients",
        sa.Column("order_index", sa.Integer(), nullable=False, server_default="0"),
    )
    op.alter_column(
        "ingredients",
        "quantity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=False,
    )
    op.alter_column(
        "ingredients", "unit", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.create_index("idx_ingredient_recipe", "ingredients", ["recipe_id"], unique=False)
    op.create_index(
        "idx_ingredient_recipe_order",
        "ingredients",
        ["recipe_id", "order_index"],
        unique=False,
    )
    op.add_column(
        "instructions",
        sa.Column(
            "title", sa.String(length=255), nullable=False, server_default="Step"
        ),
    )
    op.create_index(
        "idx_instruction_recipe_step",
        "instructions",
        ["recipe_id", "step_number"],
        unique=False,
    )
    op.create_index(
        "idx_permission_recipe_role",
        "recipe_permissions",
        ["recipe_id", "role"],
        unique=False,
    )
    op.create_index(
        "idx_permission_user_recipe",
        "recipe_permissions",
        ["user_id", "recipe_id"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_user_recipe_permission", "recipe_permissions", ["user_id", "recipe_id"]
    )
    op.add_column(
        "recipes", sa.Column("tags", sa.JSON(), nullable=False, server_default="[]")
    )
    op.create_index(
        "idx_security_audit_user_timestamp",
        "security_audit_logs",
        ["user_id", "timestamp"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_security_audit_user_timestamp", table_name="security_audit_logs")
    op.drop_column("recipes", "tags")
    op.drop_constraint(
        "uq_user_recipe_permission", "recipe_permissions", type_="unique"
    )
    op.drop_index("idx_permission_user_recipe", table_name="recipe_permissions")
    op.drop_index("idx_permission_recipe_role", table_name="recipe_permissions")
    op.drop_index("idx_instruction_recipe_step", table_name="instructions")
    op.drop_column("instructions", "title")
    op.drop_index("idx_ingredient_recipe_order", table_name="ingredients")
    op.drop_index("idx_ingredient_recipe", table_name="ingredients")
    op.alter_column(
        "ingredients", "unit", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "ingredients",
        "quantity",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        nullable=True,
    )
    op.drop_column("ingredients", "order_index")
    op.drop_column("ingredients", "subtext")
    # ### end Alembic commands ###
