"""remove_recipe_images_table

Revision ID: 7bca4308db77
Revises: f7c0a4e46756
Create Date: 2025-10-29 16:32:34.846611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bca4308db77'
down_revision = 'f7c0a4e46756'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_image_filename', table_name='recipe_images')
    op.drop_index('idx_image_recipe', table_name='recipe_images')
    op.drop_index('ix_recipe_images_filename', table_name='recipe_images')
    op.drop_index('ix_recipe_images_id', table_name='recipe_images')
    op.drop_index('ix_recipe_images_recipe_id', table_name='recipe_images')
    op.drop_table('recipe_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mime_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('alt_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('uploaded_by', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='recipe_images_recipe_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='recipe_images_uploaded_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='recipe_images_pkey')
    )
    op.create_index('ix_recipe_images_recipe_id', 'recipe_images', ['recipe_id'], unique=False)
    op.create_index('ix_recipe_images_id', 'recipe_images', ['id'], unique=False)
    op.create_index('ix_recipe_images_filename', 'recipe_images', ['filename'], unique=False)
    op.create_index('idx_image_recipe', 'recipe_images', ['recipe_id'], unique=False)
    op.create_index('idx_image_filename', 'recipe_images', ['filename'], unique=False)
    # ### end Alembic commands ###