"""Create all database tables

Revision ID: 81813866155b
Revises: 4a2646f0504e
Create Date: 2025-10-29 02:11:40.147959

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "81813866155b"
down_revision = "4a2646f0504e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recipes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cooking_time", sa.Integer(), nullable=True),
        sa.Column("serving_size", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_recipe_cooking_time", "recipes", ["cooking_time"], unique=False
    )
    op.create_index("idx_recipe_created_at", "recipes", ["created_at"], unique=False)
    op.create_index("idx_recipe_title_search", "recipes", ["title"], unique=False)
    op.create_index(
        op.f("ix_recipes_created_at"), "recipes", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_recipes_id"), "recipes", ["id"], unique=False)
    op.create_index(op.f("ix_recipes_title"), "recipes", ["title"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_email", "users", ["email"], unique=False)
    op.create_index("idx_user_username", "users", ["username"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=50), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_ingredient_name", "ingredients", ["name"], unique=False)
    op.create_index("idx_ingredient_recipe", "ingredients", ["recipe_id"], unique=False)
    op.create_index(op.f("ix_ingredients_id"), "ingredients", ["id"], unique=False)
    op.create_index(op.f("ix_ingredients_name"), "ingredients", ["name"], unique=False)
    op.create_index(
        op.f("ix_ingredients_recipe_id"), "ingredients", ["recipe_id"], unique=False
    )
    op.create_table(
        "instructions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("step_number", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("timing", sa.Integer(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_instruction_recipe_step",
        "instructions",
        ["recipe_id", "step_number"],
        unique=False,
    )
    op.create_index(op.f("ix_instructions_id"), "instructions", ["id"], unique=False)
    op.create_index(
        op.f("ix_instructions_recipe_id"), "instructions", ["recipe_id"], unique=False
    )
    op.create_table(
        "recipe_images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("original_filename", sa.String(length=255), nullable=False),
        sa.Column("file_path", sa.String(length=500), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("alt_text", sa.String(length=255), nullable=True),
        sa.Column(
            "uploaded_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("uploaded_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_image_filename", "recipe_images", ["filename"], unique=False)
    op.create_index("idx_image_recipe", "recipe_images", ["recipe_id"], unique=False)
    op.create_index(
        op.f("ix_recipe_images_filename"), "recipe_images", ["filename"], unique=False
    )
    op.create_index(op.f("ix_recipe_images_id"), "recipe_images", ["id"], unique=False)
    op.create_index(
        op.f("ix_recipe_images_recipe_id"), "recipe_images", ["recipe_id"], unique=False
    )
    op.create_table(
        "recipe_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column(
            "role", sa.Enum("OWNER", "EDITOR", name="permissionrole"), nullable=False
        ),
        sa.Column(
            "granted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("granted_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "recipe_id", name="uq_user_recipe_permission"),
    )
    op.create_index(
        "idx_permission_recipe_role",
        "recipe_permissions",
        ["recipe_id", "role"],
        unique=False,
    )
    op.create_index(
        "idx_permission_user_recipe",
        "recipe_permissions",
        ["user_id", "recipe_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipe_permissions_id"), "recipe_permissions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_recipe_permissions_recipe_id"),
        "recipe_permissions",
        ["recipe_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recipe_permissions_user_id"),
        "recipe_permissions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_recipe_permissions_user_id"), table_name="recipe_permissions"
    )
    op.drop_index(
        op.f("ix_recipe_permissions_recipe_id"), table_name="recipe_permissions"
    )
    op.drop_index(op.f("ix_recipe_permissions_id"), table_name="recipe_permissions")
    op.drop_index("idx_permission_user_recipe", table_name="recipe_permissions")
    op.drop_index("idx_permission_recipe_role", table_name="recipe_permissions")
    op.drop_table("recipe_permissions")
    op.drop_index(op.f("ix_recipe_images_recipe_id"), table_name="recipe_images")
    op.drop_index(op.f("ix_recipe_images_id"), table_name="recipe_images")
    op.drop_index(op.f("ix_recipe_images_filename"), table_name="recipe_images")
    op.drop_index("idx_image_recipe", table_name="recipe_images")
    op.drop_index("idx_image_filename", table_name="recipe_images")
    op.drop_table("recipe_images")
    op.drop_index(op.f("ix_instructions_recipe_id"), table_name="instructions")
    op.drop_index(op.f("ix_instructions_id"), table_name="instructions")
    op.drop_index("idx_instruction_recipe_step", table_name="instructions")
    op.drop_table("instructions")
    op.drop_index(op.f("ix_ingredients_recipe_id"), table_name="ingredients")
    op.drop_index(op.f("ix_ingredients_name"), table_name="ingredients")
    op.drop_index(op.f("ix_ingredients_id"), table_name="ingredients")
    op.drop_index("idx_ingredient_recipe", table_name="ingredients")
    op.drop_index("idx_ingredient_name", table_name="ingredients")
    op.drop_table("ingredients")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index("idx_user_username", table_name="users")
    op.drop_index("idx_user_email", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_recipes_title"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_id"), table_name="recipes")
    op.drop_index(op.f("ix_recipes_created_at"), table_name="recipes")
    op.drop_index("idx_recipe_title_search", table_name="recipes")
    op.drop_index("idx_recipe_created_at", table_name="recipes")
    op.drop_index("idx_recipe_cooking_time", table_name="recipes")
    op.drop_table("recipes")
    # ### end Alembic commands ###
