"""Add security audit log table

Revision ID: f7c0a4e46756
Revises: 81813866155b
Create Date: 2025-10-29 03:24:57.115997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c0a4e46756'
down_revision = '81813866155b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('security_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('success', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_security_audit_event_risk', 'security_audit_logs', ['event_type', 'risk_level'], unique=False)
    op.create_index('idx_security_audit_ip_timestamp', 'security_audit_logs', ['ip_address', 'timestamp'], unique=False)
    op.create_index('idx_security_audit_timestamp_risk', 'security_audit_logs', ['timestamp', 'risk_level'], unique=False)
    op.create_index('idx_security_audit_user_timestamp', 'security_audit_logs', ['user_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_event_type'), 'security_audit_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_id'), 'security_audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_ip_address'), 'security_audit_logs', ['ip_address'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_risk_level'), 'security_audit_logs', ['risk_level'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_session_id'), 'security_audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_timestamp'), 'security_audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_security_audit_logs_user_id'), 'security_audit_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_audit_logs_user_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_timestamp'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_session_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_risk_level'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_ip_address'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_id'), table_name='security_audit_logs')
    op.drop_index(op.f('ix_security_audit_logs_event_type'), table_name='security_audit_logs')
    op.drop_index('idx_security_audit_user_timestamp', table_name='security_audit_logs')
    op.drop_index('idx_security_audit_timestamp_risk', table_name='security_audit_logs')
    op.drop_index('idx_security_audit_ip_timestamp', table_name='security_audit_logs')
    op.drop_index('idx_security_audit_event_risk', table_name='security_audit_logs')
    op.drop_table('security_audit_logs')
    # ### end Alembic commands ###